# Generated by Django 3.2.4 on 2021-07-14 11:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_editorjs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0004_auto_20210714_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=django_editorjs.fields.EditorJsField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 11, 16, 21, 411193, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 11, 16, 21, 414054, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reply',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 11, 16, 21, 415051, tzinfo=utc)),
        ),
    ]
