# Generated by Django 3.2.4 on 2021-07-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0019_auto_20210715_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date_posted',
            field=models.DateTimeField(default='django.utils.timezone.now'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='date_posted',
            field=models.DateTimeField(default='django.utils.timezone.now'),
        ),
    ]
