# Generated by Django 3.2.4 on 2021-07-18 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0025_alter_comments_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
    ]
