# Generated by Django 3.2.4 on 2021-07-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0030_profile_name_for_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
