# Generated by Django 3.2.4 on 2021-07-20 07:12

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0031_comments_is_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='\nwhile adding images use percentages to get best Results'),
        ),
    ]
