# Generated by Django 3.2.4 on 2021-07-21 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0033_alter_blogpost_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='slug',
        ),
    ]
